#!/usr/bin/env python

Import("env")

env_tbloader = env.Clone()

env_tbloader.Append(CPPPATH=["src/", "src/map/"])

sources = [
    Glob("*.cpp"),
    Glob("src/*.cpp"),
    Glob("src/builders/*.cpp"),
    Glob("src/map/*.cpp")
]

module_obj = []

env_tbloader.add_source_files(module_obj, sources)
env.modules_sources += module_obj